import { createSchema } from "@ponder/core";

export default createSchema((p) => ({
  lendingVaults: p.createTable({
    id: p.hex(),
    totalAssets: p.bigint(),
    totalSupply: p.bigint(),
    totalUnrealizedInterest: p.bigint(),
    totalOutstandingLoans: p.bigint(),
    totalLoansIssued: p.int(),
    totalInterestEarned: p.bigint(),
    totalDefaultedAmount: p.bigint(),
    totalWrittenOff: p.bigint(),
    activeLoansCount: p.int(),
    defaultedLoansCount: p.int(),
    repaidLoansCount: p.int(),
    totalDeposited: p.bigint(),
    totalWithdrawn: p.bigint(),
    initialSharePrice: p.string(),
    currentSharePrice: p.string(),
    averageInterestRate: p.string(),
    utilizationRate: p.string(),
    kycEnabled: p.boolean(),
    kycRegistry: p.hex().optional(),
    createdAt: p.bigint(),
    lastUpdateAt: p.bigint(),
  }),

  lenders: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    address: p.hex(),
    shares: p.bigint(),
    deposited: p.bigint(),
    withdrawn: p.bigint(),
    realizedGains: p.bigint(),
    unrealizedGains: p.bigint(),
    totalInterestEarned: p.bigint(),
    lastInterestUpdate: p.bigint(),
    firstDepositTime: p.bigint().optional(),
    lastActivityTime: p.bigint(),
    depositCount: p.int(),
    withdrawCount: p.int(),
    currentValue: p.bigint(),
  }),

  borrowers: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    address: p.hex(),
    totalBorrowed: p.bigint(),
    totalRepaid: p.bigint(),
    totalInterestPaid: p.bigint(),
    totalPrincipalPaid: p.bigint(),
    currentOutstanding: p.bigint(),
    currentInterestAccrued: p.bigint(),
    totalLoansCount: p.int(),
    activeLoansCount: p.int(),
    repaidLoansCount: p.int(),
    defaultedLoansCount: p.int(),
    averageInterestRate: p.string(),
    onTimePaymentRate: p.string(),
    defaultRate: p.string(),
    kycVerified: p.boolean(),
    kycExpiration: p.bigint().optional(),
    firstLoanTime: p.bigint().optional(),
    lastActivityTime: p.bigint(),
  }),

  loans: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    loanId: p.bigint(),
    borrowerId: p.string().references("borrowers.id"),
    principal: p.bigint(),
    interestRateBps: p.int(),
    interestType: p.string(),
    compoundingPeriod: p.string(),
    startTimestamp: p.bigint(),
    maturityTimestamp: p.bigint().optional(),
    gracePeriodDays: p.int(),
    disbursementTimestamp: p.bigint(),
    minPaymentAmount: p.bigint(),
    lateFeeRateBps: p.int(),
    outstandingPrincipal: p.bigint(),
    accruedInterest: p.bigint(),
    totalInterestPaid: p.bigint(),
    totalPrincipalPaid: p.bigint(),
    status: p.string(),
    lastInterestUpdateTimestamp: p.bigint(),
    lastPaymentTimestamp: p.bigint().optional(),
    defaultTimestamp: p.bigint().optional(),
    totalPaid: p.bigint(),
    totalOwed: p.bigint(),
    isLate: p.boolean(),
    daysLate: p.int(),
    currentInterestRate: p.int(),
    agreementHash: p.hex(),
    agreementContract: p.hex().optional(),
    paymentCount: p.int(),
    latePaymentCount: p.int(),
  }),

  loanPayments: p.createTable({
    id: p.string(),
    loanId: p.string().references("loans.id"),
    borrowerId: p.string().references("borrowers.id"),
    payer: p.hex(),
    totalPayment: p.bigint(),
    interestPaid: p.bigint(),
    principalPaid: p.bigint(),
    lateFeesPaid: p.bigint(),
    remainingPrincipal: p.bigint(),
    remainingInterest: p.bigint(),
    timestamp: p.bigint(),
    daysLate: p.int(),
    wasLate: p.boolean(),
    txHash: p.hex(),
    blockNumber: p.bigint(),
  }),

  depositRequests: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    lenderId: p.string().references("lenders.id"),
    requestId: p.bigint(),
    receiver: p.hex(),
    assetsRequested: p.bigint(),
    assetsProcessed: p.bigint(),
    sharesIssued: p.bigint(),
    status: p.string(),
    fullyExecuted: p.boolean(),
    requestTime: p.bigint(),
    lastExecuteTime: p.bigint().optional(),
    executionSharePrice: p.string().optional(),
  }),

  depositExecutions: p.createTable({
    id: p.string(),
    requestId: p.string().references("depositRequests.id"),
    vaultId: p.hex().references("lendingVaults.id"),
    assetsProcessed: p.bigint(),
    sharesIssued: p.bigint(),
    fullyExecuted: p.boolean(),
    txHash: p.hex(),
    blockNumber: p.bigint(),
    timestamp: p.bigint(),
  }),

  withdrawRequests: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    lenderId: p.string().references("lenders.id"),
    requestId: p.bigint(),
    receiver: p.hex(),
    sharesRequested: p.bigint(),
    sharesProcessed: p.bigint(),
    assetsReturned: p.bigint(),
    status: p.string(),
    fullyExecuted: p.boolean(),
    requestTime: p.bigint(),
    lastExecuteTime: p.bigint().optional(),
    executionSharePrice: p.string().optional(),
  }),

  withdrawExecutions: p.createTable({
    id: p.string(),
    requestId: p.string().references("withdrawRequests.id"),
    vaultId: p.hex().references("lendingVaults.id"),
    sharesProcessed: p.bigint(),
    assetsReturned: p.bigint(),
    feeShares: p.bigint().optional(),
    fullyExecuted: p.boolean(),
    txHash: p.hex(),
    blockNumber: p.bigint(),
    timestamp: p.bigint(),
  }),

  adminWithdrawals: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    shareholder: p.hex(),
    receiver: p.hex(),
    shares: p.bigint(),
    assets: p.bigint(),
    feeShares: p.bigint(),
    feeRecipient: p.hex().optional(),
    timestamp: p.bigint(),
    txHash: p.hex(),
    blockNumber: p.bigint(),
  }),

  interestSnapshots: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    totalUnrealizedInterest: p.bigint(),
    totalOutstandingLoans: p.bigint(),
    activeLoansCount: p.int(),
    averageInterestRate: p.string(),
    utilizationRate: p.string(),
    totalAssets: p.bigint(),
    totalSupply: p.bigint(),
    sharePrice: p.string(),
    timestamp: p.bigint(),
    blockNumber: p.bigint(),
  }),

  dailyLendingSnapshots: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    day: p.int(),
    timestamp: p.bigint(),
    totalAssets: p.bigint(),
    totalSupply: p.bigint(),
    totalOutstandingLoans: p.bigint(),
    totalUnrealizedInterest: p.bigint(),
    loansIssuedCount: p.int(),
    loansRepaidCount: p.int(),
    totalLent: p.bigint(),
    totalRepaid: p.bigint(),
    interestEarned: p.bigint(),
    utilizationRate: p.string(),
    averageInterestRate: p.string(),
    sharePrice: p.string(),
    defaultedAmount: p.bigint(),
    writtenOffAmount: p.bigint(),
  }),

  accessControlRoles: p.createTable({
    id: p.string(),
    vaultId: p.hex().references("lendingVaults.id"),
    roleHash: p.hex(),
    roleName: p.string(),
    adminRoleHash: p.hex(),
    adminRoleName: p.string(),
    memberCount: p.int(),
    updatedAt: p.bigint(),
  }),

  accessControlRoleMembers: p.createTable({
    id: p.string(),
    roleId: p.string().references("accessControlRoles.id"),
    account: p.hex(),
    isActive: p.boolean(),
    grantedAt: p.bigint(),
    revokedAt: p.bigint().optional(),
    grantTxHash: p.hex(),
    revokeTxHash: p.hex().optional(),
    grantBlockNumber: p.bigint(),
    revokeBlockNumber: p.bigint().optional(),
    updatedAt: p.bigint(),
  }),

  accessControlRoleEvents: p.createTable({
    id: p.string(),
    roleId: p.string().references("accessControlRoles.id"),
    account: p.hex().optional(),
    adminRoleHash: p.hex().optional(),
    adminRoleName: p.string().optional(),
    eventType: p.string(),
    txHash: p.hex(),
    blockNumber: p.bigint(),
    timestamp: p.bigint(),
  }),
}));
